# Glass Dataset's

In [89]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [90]:
data = pd.read_csv('Dataset/glass.csv')
data

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [91]:
# spliting data into ddependent and independent

x = data.iloc[:,0:9]
y = data.iloc[:,9]


In [92]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
dtypes: float64(9)
memory usage: 15.2 KB


In [99]:
# splitting trainnig dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x , y , test_size = .30, random_state = 1)

print(x_train)
print(x_test)
print(y_train)
print(y_test)

          RI     Na    Mg    Al     Si     K    Ca    Ba    Fe
187  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00
174  1.52058  12.85  1.61  2.17  72.18  0.76  9.70  0.24  0.51
56   1.51215  12.99  3.47  1.12  72.98  0.62  8.35  0.00  0.31
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00
55   1.51769  12.45  2.71  1.29  73.70  0.56  9.06  0.00  0.24
..       ...    ...   ...   ...    ...   ...   ...   ...   ...
203  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00
137  1.51711  12.89  3.62  1.57  72.96  0.61  8.11  0.00  0.00
72   1.51593  13.09  3.59  1.52  73.10  0.67  7.83  0.00  0.00
140  1.51690  13.33  3.54  1.61  72.54  0.68  8.11  0.00  0.00
37   1.51797  12.74  3.48  1.35  72.96  0.64  8.68  0.00  0.00

[149 rows x 9 columns]
          RI     Na    Mg    Al     Si     K     Ca    Ba    Fe
108  1.52222  14.43  0.00  1.00  72.67  0.10  11.52  0.00  0.08
206  1.51645  14.94  0.00  1.87  73.11  0.00   8.67  1.38  0.00
106  1.53125  10.73  0.00  2

In [100]:
# applying Logistic Regression

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression ()
lr.fit (x_train, y_train)

E:\Software Programs Files\Anaconda-Data\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [101]:
# Using Min-MAx
from sklearn.preprocessing import MinMaxScaler      # range 
mms = MinMaxScaler()
x_train_norm = mms.fit_transform (x_train) #fit and transform
x_test_norm = mms.transform (x_test) # only transform

In [102]:
# accuracy check
predict = lr.predict (x_test_norm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predict))


0.47692307692307695


In [97]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test, predict)

print(cm)

[[18  1  0  0  0  0]
 [ 4  4  1  2  1  0]
 [ 4  1  1  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  2  0  2]]


In [98]:
# normal Way --> 70.7% {}
# using MinMAx ---> 47.6% {}
# 