In [1]:
import numpy as np
import pandas as pd


df= pd.read_csv("textclass.csv")
df



Title  Label
0  I love India. India!      0
1         India is best      1
2    Germany beats both      1

In [3]:
y=df["Label"]
x=df["Title"]
y

0    0
1    1
2    1
Name: Label, dtype: int64

In [4]:
				  					  
###############################################################################################
# the words need to be encoded as integers or floating point values for use as input to a ML algorithm					  
				
#################################################################################################				
# Create bag of words
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer() 
"""CountVectorizer : vector is returned with a length of the entire vocabulary 
and an integer count for the number of
times each word appeared in the document."""



count.fit(x)  


print(count.vocabulary_) 
#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2}



{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2}


In [7]:

bag_of_words = count.fit_transform(x)
print(bag_of_words)




  (0, 6)	1
  (0, 4)	2
  (1, 4)	1
  (1, 5)	1
  (1, 1)	1
  (2, 3)	1
  (2, 0)	1
  (2, 2)	1


In [8]:
# Create feature matrix
X = bag_of_words.toarray()
print(X)
"""
#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2} 
# 7 columns because we have 7 seperate words in our dataset and 3 rows because we have 3 rows in dataset
[[0 0 0 0 2 0 1]  
 [0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0]]
""" 



[[0 0 0 0 2 0 1]
 [0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0]]


"\n#{'love': 6, 'india': 4, 'is': 5, 'best': 1, 'germany': 3, 'beats': 0, 'both': 2} \n# 7 columns because we have 7 seperate words in our dataset and 3 rows because we have 3 rows in dataset\n[[0 0 0 0 2 0 1]  \n [0 1 0 0 1 1 0]\n [1 0 1 1 0 0 0]]\n"

In [13]:


# Create multinomial naive Bayes object with prior probabilities of each class
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB(class_prior=[0.35, 0.60])

# Train model
model = clf.fit(X, y)


#xtest=np.array(["India is my country. I want to go germany, India"])
xtest=np.array(["love germany"])
xtest=count.transform(xtest)
print(xtest)
xtest=xtest.toarray()
xtest


  (0, 3)	1
  (0, 6)	1


array([[0, 0, 0, 1, 0, 0, 1]], dtype=int64)

In [14]:

pred=clf.predict(xtest)

# Create new observation
#new_observation = [[0, 0, 0, 1, 0, 1, 0]]    
#new_observation = [[0, 0, 0, 1, 1, 1, 1]]    
#new_observation = [[0, 0, 1, 1, 1, 1, 1]]    


# Predict new observation's class
#pred = model.predict(new_observation)
print(pred)
					  
				  

[1]
