In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Dataset/Fruit.csv')
df


color  diameter  label
0   green         3  Mango
1  yellow         3  Mango
2     red         1  Grape
3     red         1  Grape
4  yellow         3  Lemon

In [4]:
X=df.iloc[:,0:2]
y=df.iloc[:,2]
y

0    Mango
1    Mango
2    Grape
3    Grape
4    Lemon
Name: label, dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X.iloc[:, 0] = X_labelencoder.fit_transform(X.iloc[:, 0])
print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

y=y.reshape(-1,1)
print(y)





   color  diameter
0      0         3
1      2         3
2      1         1
3      1         1
4      2         3
[2 2 0 0 1]
[[2]
 [2]
 [0]
 [0]
 [1]]


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
"""
criterion: It defines the function to measure the impurity. Sklearn supports “gini” criteria for Gini Index
 & “entropy” for Information Gain. By default, it takes “gini” value.
 
max_depth: The max_depth parameter denotes maximum depth of the tree.
"""


'\ncriterion: It defines the function to measure the impurity. Sklearn supports “gini” criteria for Gini Index\n & “entropy” for Information Gain. By default, it takes “gini” value.\n \nmax_depth: The max_depth parameter denotes maximum depth of the tree.\n'

In [7]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(criterion = "entropy",max_depth=2)
decision_tree.fit(X_train, y_train)
predictValues =decision_tree.predict(X_test)

predictValues




array([0])

In [8]:
from sklearn.metrics import accuracy_score
import numpy as np

print(accuracy_score(y_test, predictValues))


1.0


In [9]:
data_feature_names = [ 'color', 'diameter']
!pip install graphviz
from sklearn.tree import export_graphviz
from sklearn import tree
from graphviz import Source
from IPython.display import SVG
from IPython.display import display

graph = Source(tree.export_graphviz(decision_tree, out_file=None, feature_names=data_feature_names, filled = True,rounded=True))
display(SVG(graph.pipe(format='svg')))

ExecutableNotFound: failed to execute ['dot', '-Kdot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH