In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


healthData = pd.read_csv ('Health.csv')
#print(healthData)


#X = healthData.iloc [:,:-1].values
X = healthData.iloc [:,0:3]  # X is independent variable
y = healthData.iloc [:,3]  #dependent variable

print(X)
print(y)

  Ethnicity  Height (CM)  Weight (Kg)
0     White        186.0         90.0
1   African        185.0         98.0
2     Asian        175.0         80.0
3     White        180.0         88.0
4     Asian        178.0          NaN
5     Asian        172.0         72.0
6   African        178.0         75.0
7     White          NaN         89.0
8   African        186.0         90.0
0    Yes
1     No
2     No
3    Yes
4     No
5    Yes
6     No
7    Yes
8    Yes
Name: Will survive till 70, dtype: object


In [4]:
#==============================================================================
# Handle the missing values, we can see that in dataset there are some missing
# values, we will use strategy to impute mean of column values in these places
#==============================================================================

from sklearn.impute import SimpleImputer
# First create an Imputer , Stratergy means what we want to write in place of missed value
missingValueImputer = SimpleImputer (missing_values = np.nan, strategy = 'mean')  #if missing values are represented by 9999 then write same here
# Set which columns imputer should perform   # update values of X with new values

X.iloc[:,1:3] = missingValueImputer.fit_transform (X.iloc[:,1:3])


print(X)
print(y)

  Ethnicity  Height (CM)  Weight (Kg)
0     White        186.0        90.00
1   African        185.0        98.00
2     Asian        175.0        80.00
3     White        180.0        88.00
4     Asian        178.0        85.25
5     Asian        172.0        72.00
6   African        178.0        75.00
7     White        180.0        89.00
8   African        186.0        90.00
0    Yes
1     No
2     No
3    Yes
4     No
5    Yes
6     No
7    Yes
8    Yes
Name: Will survive till 70, dtype: object


In [7]:
#==============================================================================
# Encode the categorial data. So now instead of character values we will have
# corresponding numerical values
#==============================================================================

from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X.iloc[:, 0] = X_labelencoder.fit_transform(X.iloc[:, 0])
print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

from sklearn.model_selection import train_test_split

#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 0)

   Ethnicity  Height (CM)  Weight (Kg)
0          2        186.0        90.00
1          0        185.0        98.00
2          1        175.0        80.00
3          2        180.0        88.00
4          1        178.0        85.25
5          1        172.0        72.00
6          0        178.0        75.00
7          2        180.0        89.00
8          0        186.0        90.00
[1 0 0 1 0 1 0 1 1]


In [8]:
from sklearn.model_selection import train_test_split

#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 0)

X_train

Ethnicity  Height (CM)  Weight (Kg)
1          0        185.0        98.00
4          1        178.0        85.25
8          0        186.0        90.00
6          0        178.0        75.00
3          2        180.0        88.00
0          2        186.0        90.00
5          1        172.0        72.00

In [9]:
#==============================================================================
# Feature scaling is to bring all the independent variables in a dataset into
# same scale, to avoid any variable dominating  the model. Here we will not 
# transform the dependent variables.
#==============================================================================

from sklearn.preprocessing import StandardScaler
independent_scalar = StandardScaler()
X_train = independent_scalar.fit_transform (X_train) #fit and transform
X_test = independent_scalar.transform (X_test) # only transform
print(X_train)

[[-1.02899151  0.88159065  1.48988518]
 [ 0.17149859 -0.55834074 -0.02546812]
 [-1.02899151  1.08729513  0.53907526]
 [-1.02899151 -0.55834074 -1.24369333]
 [ 1.37198868 -0.14693177  0.30137279]
 [ 1.37198868  1.08729513  0.53907526]
 [ 0.17149859 -1.79256765 -1.60024704]]


In [10]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.predict(X_test)


array([1, 1])