In [35]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [36]:


flatdata = pd.read_csv ('Health.csv')
X = flatdata.iloc [:,0:3]
y = flatdata.iloc [:,3]
#print(y)
#X
flatdata
X

Ethnicity  Height (CM)  Weight (Kg)
0     White        186.0         90.0
1   African        185.0         98.0
2     Asian        175.0         80.0
3     White        180.0         88.0
4     Asian        178.0          NaN
5     Asian        172.0         72.0
6   African        178.0         75.0
7     White          NaN         89.0
8   African        186.0         90.0

In [37]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Ethnicity    9 non-null      object 
 1   Height (CM)  8 non-null      float64
 2   Weight (Kg)  8 non-null      float64
dtypes: float64(2), object(1)
memory usage: 344.0+ bytes


In [38]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
X.iloc[:, 0] = lb.fit_transform(X.iloc[:, 0])
#print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

X

[1 0 0 1 0 1 0 1 1]


Ethnicity  Height (CM)  Weight (Kg)
0          2        186.0         90.0
1          0        185.0         98.0
2          1        175.0         80.0
3          2        180.0         88.0
4          1        178.0          NaN
5          1        172.0         72.0
6          0        178.0         75.0
7          2          NaN         89.0
8          0        186.0         90.0

In [39]:
from sklearn.impute import SimpleImputer
# First create an Imputer , Stratergy means what we want to write in place of missed value
mss = SimpleImputer (missing_values = np.nan, strategy = 'mean')  
 
# Set which columns imputer should perform
mss = mss.fit (X.iloc[:,1:3])
# update values of X with new values
X.iloc[:,1:3] = mss.transform(X.iloc[:,1:3])

print(X)


   Ethnicity  Height (CM)  Weight (Kg)
0          2        186.0        90.00
1          0        185.0        98.00
2          1        175.0        80.00
3          2        180.0        88.00
4          1        178.0        85.25
5          1        172.0        72.00
6          0        178.0        75.00
7          2        180.0        89.00
8          0        186.0        90.00


In [40]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================


from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = .20, random_state = 0)


#print("splitting done")
#print(X_train)		
#print(y_train)	
#print(X_test)	
X_train



Ethnicity  Height (CM)  Weight (Kg)
1          0        185.0        98.00
4          1        178.0        85.25
8          0        186.0        90.00
6          0        178.0        75.00
3          2        180.0        88.00
0          2        186.0        90.00
5          1        172.0        72.00

In [41]:
#==============================================================================
# Fit the Logistic regression to the train data. Logistic regression is a 
# linear classifier after which the data is divided by a straight line.
#==============================================================================
from sklearn.linear_model import LogisticRegression
LRClassifier = LogisticRegression ()
LRClassifier.fit (X_train, y_train)

#==============================================================================
# Predict the values 
#==============================================================================

prediction = LRClassifier.predict (X_test)
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, prediction))


prediction 

1.0


array([1, 0])

In [42]:
#==============================================================================
# Create confusion matrix to evaluate performance of data
#==============================================================================
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix (y_test, prediction)

print(confusionMatrix)

X_test
print("av",y_test)
print("p",prediction)

[[1 0]
 [0 1]]
av [1 0]
p [1 0]
